# Breast Cancer Detection

In [2]:
import numpy as np 
import pandas as pd 
import torch
from sklearn.model_selection import train_test_split 
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [3]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head()

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0    842302         M        17.99         10.38          122.80     1001.0   
1    842517         M        20.57         17.77          132.90     1326.0   
2  84300903         M        19.69         21.25          130.00     1203.0   
3  84348301         M        11.42         20.38           77.58      386.1   
4  84358402         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   ...  texture_worst  perimeter_worst  area_worst  smoothness_worst  \
0  ...          17.33           184.60      2019.0            0.1622   
1  ...          23.41           158.80      1956.0            0.1238   
2  ...          25.53           152.50      1709.0            0.1444   
3  ...          26.50            98.87       567.7            0.2098   
4  ...          16.67           152.20      1575.0            0.1374   

   compactness_worst  concavity_worst  concave points_worst  symmetry_worst  \
0             0.6656           0.7119                0.2654          0.4601   
1             0.1866           0.2416                0.1860          0.2750   
2             0.4245           0.4504                0.2430          0.3613   
3             0.8663           0.6869                0.2575          0.6638   
4             0.2050           0.4000                0.1625          0.2364   

   fractal_dimension_worst  Unnamed: 32  
0                  0.11890          NaN  
1                  0.08902          NaN  
2                  0.08758          NaN  
3                  0.17300          NaN  
4                  0.07678          NaN  

[5 rows x 33 columns]

In [4]:
df.shape

(569, 33)

In [6]:
df.drop(columns=['id', 'Unnamed: 32'], inplace=True) 

In [7]:
df.head() 

diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0         M        17.99         10.38          122.80     1001.0   
1         M        20.57         17.77          132.90     1326.0   
2         M        19.69         21.25          130.00     1203.0   
3         M        11.42         20.38           77.58      386.1   
4         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   symmetry_mean  ...  radius_worst  texture_worst  perimeter_worst  \
0         0.2419  ...         25.38          17.33           184.60   
1         0.1812  ...         24.99          23.41           158.80   
2         0.2069  ...         23.57          25.53           152.50   
3         0.2597  ...         14.91          26.50            98.87   
4         0.1809  ...         22.54          16.67           152.20   

   area_worst  smoothness_worst  compactness_worst  concavity_worst  \
0      2019.0            0.1622             0.6656           0.7119   
1      1956.0            0.1238             0.1866           0.2416   
2      1709.0            0.1444             0.4245           0.4504   
3       567.7            0.2098             0.8663           0.6869   
4      1575.0            0.1374             0.2050           0.4000   

   concave points_worst  symmetry_worst  fractal_dimension_worst  
0                0.2654          0.4601                  0.11890  
1                0.1860          0.2750                  0.08902  
2                0.2430          0.3613                  0.08758  
3                0.2575          0.6638                  0.17300  
4                0.1625          0.2364                  0.07678  

[5 rows x 31 columns]

## Train Test Split 

In [8]:
X_train, X_test, y_train, y_test = train_test_split(df.iloc[:,1:], df.iloc[:,0], test_size=0.2)

## Scaling

In [9]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [10]:
X_train

array([[-1.37602996, -1.4642733 , -1.24603236, ..., -0.16046401,
         0.22017841,  2.19563273],
       [-1.58013437, -1.41174676, -1.54091732, ..., -0.42431107,
         0.13357098,  1.10491404],
       [ 0.23806399,  1.06385191,  0.27542151, ...,  0.73370122,
         0.66581301,  0.25651758],
       ...,
       [-0.79270719,  0.12522548, -0.83039709, ..., -1.28659605,
        -0.53724294, -0.44089763],
       [-0.6755741 , -0.505093  , -0.72871262, ..., -1.0695067 ,
        -0.26324852, -0.86428991],
       [ 0.12678756,  1.76039951,  0.05722359, ..., -0.87200093,
        -0.87107522, -1.05825515]])

In [11]:
y_train

504    B
525    B
65     M
341    B
145    B
      ..
110    B
397    B
522    B
350    B
462    B
Name: diagnosis, Length: 455, dtype: object

### Label Encoding

In [12]:
encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.transform(y_test)

### Numpy array to pytorch tensor

In [13]:
X_train_tensor = torch.from_numpy(X_train)
X_test_tensor = torch.from_numpy(X_test)
y_train_tensor = torch.from_numpy(y_train)
y_test_tensor = torch.from_numpy(y_test)

In [14]:
X_train_tensor.shape

torch.Size([455, 30])

In [15]:
y_train_tensor.shape

torch.Size([455])

### Defining the model

In [16]:
class MySimpleNN(): 
    def __init__(self, X):
        self.weights = torch.rand(X.shape[1], 1, dtype=torch.float64, requires_grad=True)
        self.bias = torch.zeros(1, dtype=torch.float64, requires_grad=True) 

    def forward(self, X): 
        z = torch.matmul(X, self.weights) + self.bias 
        y_pred = torch.sigmoid(z) 
        return y_pred 
    
    def loss_function(self, y_pred, y):
        # Clamp Predictions to avoid log(0)
        epsilon = 1e-7
        y_pred = torch.clamp(y_pred, epsilon, 1-epsilon)
    
        # Calculate loss 
        loss = -(y_train_tensor * torch.log(y_pred) + (1 - y_train_tensor) * torch.log(1 - y_pred)).mean() 

        return loss 

In [17]:
learning_rate = 0.1
epochs = 25 

#### Training Pipeline

In [18]:
model = MySimpleNN(X_train_tensor)

for epoch in range(epochs):

    #Forward pass 
    y_pred = model.forward(X_train_tensor)

    # Loss calculate 
    loss = model.loss_function(y_pred, y_train_tensor)

    #backward loss 
    loss.backward() 

    #Parameters update
    with torch.no_grad():
        model.weights -= learning_rate * model.weights.grad 
        model.bias -= learning_rate * model.bias.grad 

    # zero gradients 
    model.weights.grad.zero_() 
    model.bias.grad.zero_()

    # print loss in each epoch 
    print(f"Epoch: {epoch + 1}, Loss: {loss.item()}")

Epoch: 1, Loss: 3.711674007845521
Epoch: 2, Loss: 3.5939553720723736
Epoch: 3, Loss: 3.470240374816736
Epoch: 4, Loss: 3.3412531642655035
Epoch: 5, Loss: 3.2066861451999826
Epoch: 6, Loss: 3.0664679083899435
Epoch: 7, Loss: 2.9212809440197507
Epoch: 8, Loss: 2.7666217331592513
Epoch: 9, Loss: 2.599104472045081
Epoch: 10, Loss: 2.42941679984572
Epoch: 11, Loss: 2.2553189147318973
Epoch: 12, Loss: 2.080950442547839
Epoch: 13, Loss: 1.9042834250826361
Epoch: 14, Loss: 1.7346379867497286
Epoch: 15, Loss: 1.5720760646048735
Epoch: 16, Loss: 1.4217868332109547
Epoch: 17, Loss: 1.2809651221072376
Epoch: 18, Loss: 1.157271930327096
Epoch: 19, Loss: 1.0522899938849672
Epoch: 20, Loss: 0.9667453751317144
Epoch: 21, Loss: 0.9002225188234392
Epoch: 22, Loss: 0.8509789788811187
Epoch: 23, Loss: 0.8160348584308419
Epoch: 24, Loss: 0.791757720687769
Epoch: 25, Loss: 0.7747259698456912


In [19]:
model.bias

tensor([-0.1541], dtype=torch.float64, requires_grad=True)

In [20]:
model.weights[:5]

tensor([[ 0.1753],
        [ 0.2544],
        [-0.2868],
        [ 0.2031],
        [-0.2869]], dtype=torch.float64, grad_fn=<SliceBackward0>)

### Evaluation

In [24]:
# Model evaluation
with torch.no_grad():
    y_pred = model.forward(X_test_tensor)
    y_pred = (y_pred > 0.80).float() 
    accuracy = (y_pred == y_test_tensor).float().mean() 
    print(f"Accuracy: {accuracy.item()}")

Accuracy: 0.5470914244651794
