## Lesson 1 basic to learn Pytorch

In [1]:
import torch 
print(torch.__version__)

2.6.0+cu126


In [2]:
if torch.cuda.is_available():
    print("GPU is available")
    print(f"Using GPU: {torch.cuda.get_device_name(0)}")
else: 
    print("GPU is not available. Using CPU.")

GPU is available
Using GPU: NVIDIA GeForce GTX 1050 Ti


### Creating a Tensor

In [3]:
# Using empty 
a = torch.empty(2,3)

In [4]:
#Check type
type(a)

torch.Tensor

In [5]:
# Using zeros
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [6]:
#Using ones 
torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [7]:
#random 
torch.rand(2,3)

tensor([[0.9964, 0.3556, 0.6057],
        [0.3141, 0.4826, 0.3866]])

In [ ]:
# use of seed 
torch.manual_seed(100)
torch.rand(2,3)#

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [10]:
# using tensor 
torch.tensor([[1,2,3],[4,5,6]])

tensor([[1, 2, 3],
        [4, 5, 6]])

In [14]:
#other ways

#arange
print('using arange', torch.arange(0,10,2)) 

#using linspace
print("using linspace -> ", torch.linspace(0,10,10))

# using eye
print("using eye ->", torch.eye(5)) # Identity matrix

#Using full 
print("using full ->", torch.full((3,3), 5))

using arange tensor([0, 2, 4, 6, 8])
using linspace ->  tensor([ 0.0000,  1.1111,  2.2222,  3.3333,  4.4444,  5.5556,  6.6667,  7.7778,
         8.8889, 10.0000])
using eye -> tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])
using full -> tensor([[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]])


### Tensor Shapes

In [15]:
x = torch.tensor([[1,2,3],[4,5,6]])
x.shape

torch.Size([2, 3])

In [17]:
torch.empty_like(x) # same shape but different values

tensor([[0, 0, 0],
        [0, 0, 0]])

In [18]:
torch.zeros_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [19]:
torch.ones_like(x)

tensor([[1, 1, 1],
        [1, 1, 1]])

In [20]:
torch.rand_like(x)

RuntimeError: "check_uniform_bounds" not implemented for 'Long'

Note: The problem here is 'x' is int32 dtype variable and rand_like creates float data. Therefore, we are getting this error.

### Tensor Data Types

In [21]:
# Find data type
x.dtype

torch.int64

In [22]:
# assign data type 
torch.tensor([1.0,2.0,3.0], dtype=torch.int32)

tensor([1, 2, 3], dtype=torch.int32)

In [23]:
torch.tensor([1,2,3], dtype = torch.float32)

tensor([1., 2., 3.])

In [24]:
#using to()
x.to(torch.float32)

tensor([[1., 2., 3.],
        [4., 5., 6.]])

| **Data Type**             | **Dtype**         | **Description**                                                                                                                                                                |
|---------------------------|-------------------|--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| **32-bit Floating Point** | `torch.float32`   | Standard floating-point type used for most deep learning tasks. Provides a balance between precision and memory usage.                                                         |
| **64-bit Floating Point** | `torch.float64`   | Double-precision floating point. Useful for high-precision numerical tasks but uses more memory.                                                                               |
| **16-bit Floating Point** | `torch.float16`   | Half-precision floating point. Commonly used in mixed-precision training to reduce memory and computational overhead on modern GPUs.                                            |
| **BFloat16**              | `torch.bfloat16`  | Brain floating-point format with reduced precision compared to `float16`. Used in mixed-precision training, especially on TPUs.                                                |
| **8-bit Floating Point**  | `torch.float8`    | Ultra-low-precision floating point. Used for experimental applications and extreme memory-constrained environments (less common).                                               |
| **8-bit Integer**         | `torch.int8`      | 8-bit signed integer. Used for quantized models to save memory and computation in inference.                                                                                   |
| **16-bit Integer**        | `torch.int16`     | 16-bit signed integer. Useful for special numerical tasks requiring intermediate precision.                                                                                    |
| **32-bit Integer**        | `torch.int32`     | Standard signed integer type. Commonly used for indexing and general-purpose numerical tasks.                                                                                  |
| **64-bit Integer**        | `torch.int64`     | Long integer type. Often used for large indexing arrays or for tasks involving large numbers.                                                                                  |
| **8-bit Unsigned Integer**| `torch.uint8`     | 8-bit unsigned integer. Commonly used for image data (e.g., pixel values between 0 and 255).                                                                                    |
| **Boolean**               | `torch.bool`      | Boolean type, stores `True` or `False` values. Often used for masks in logical operations.                                                                                      |
| **Complex 64**            | `torch.complex64` | Complex number type with 32-bit real and 32-bit imaginary parts. Used for scientific and signal processing tasks.                                                               |
| **Complex 128**           | `torch.complex128`| Complex number type with 64-bit real and 64-bit imaginary parts. Offers higher precision but uses more memory.                                                                 |
| **Quantized Integer**     | `torch.qint8`     | Quantized signed 8-bit integer. Used in quantized models for efficient inference.                                                                                              |
| **Quantized Unsigned Integer** | `torch.quint8` | Quantized unsigned 8-bit integer. Often used for quantized tensors in image-related tasks.                                                                                     |


In [25]:
# answer to rand_like 
torch.rand_like(x, dtype=torch.float32)

tensor([[0.2627, 0.0428, 0.2080],
        [0.1180, 0.1217, 0.7356]])

Mathematical Operations

1. Scalar Operation

In [26]:
x = torch.rand(2,2)
x

tensor([[0.7118, 0.7876],
        [0.4183, 0.9014]])

In [27]:
# addition
x + 2
# substraction
x - 2
# multiplication
x * 3
# division
x / 3
# int division
(x * 100)//3
# mod
((x * 100)//3)%2
# power
x**2

tensor([[0.5066, 0.6203],
        [0.1750, 0.8125]])

2. Element wise operation

In [28]:
a = torch.rand(2,3)
b = torch.rand(2,3)

print(a,b)

tensor([[0.9969, 0.7565, 0.2239],
        [0.3023, 0.1784, 0.8238]]) tensor([[0.5557, 0.9770, 0.4440],
        [0.9478, 0.7445, 0.4892]])


In [29]:
# add
a + b
# sub
a - b
# multiply
a * b
# division
a / b
# power
a ** b
# mod
a % b

tensor([[0.4411, 0.7565, 0.2239],
        [0.3023, 0.1784, 0.3346]])

In [30]:
c = torch.tensor([1, -2, 3, -4])

In [31]:
# abs
torch.abs(c)

tensor([1, 2, 3, 4])

In [32]:
# negative
torch.neg(c)

tensor([-1,  2, -3,  4])

In [33]:
d = torch.tensor([1.9, 2.3, 3.7, 4.4])

In [34]:
# round
torch.round(d)

tensor([2., 2., 4., 4.])

In [35]:
# ceil
torch.ceil(d)

tensor([2., 3., 4., 5.])

In [36]:
# floor
torch.floor(d)

tensor([1., 2., 3., 4.])

In [37]:
# clamp
torch.clamp(d, min=2, max=3)

tensor([2.0000, 2.3000, 3.0000, 3.0000])

### 3. Reduction Operation

In [38]:
e = torch.randint(size=(2,3), low=0, high=10, dtype=torch.float32)
e

tensor([[8., 0., 7.],
        [0., 0., 9.]])

In [39]:
# sum
torch.sum(e)
# sum along columns
torch.sum(e, dim=0)
# sum along rows
torch.sum(e, dim=1)

tensor([15.,  9.])

In [40]:
# mean
torch.mean(e)
# mean along col
torch.mean(e, dim=0)

tensor([4., 0., 8.])

In [41]:
# median
torch.median(e)

tensor(0.)

In [42]:
# max and min
torch.max(e)
torch.min(e)

tensor(0.)

In [43]:
# product
torch.prod(e)

tensor(0.)

In [44]:
# standard deviation
torch.std(e)

tensor(4.4272)

In [45]:
# variance
torch.var(e)

tensor(19.6000)

In [46]:
# argmax
torch.argmax(e)

tensor(5)

In [47]:
# argmin
torch.argmin(e)

tensor(1)

## 4. Matrix Operations

In [48]:
f = torch.randint(size=(2,3), low=0, high=10)
g = torch.randint(size=(3,2), low=0, high=10)

print(f)
print(g)

tensor([[5, 7, 3],
        [9, 4, 0]])
tensor([[5, 7],
        [5, 9],
        [9, 7]])


In [49]:
# matrix multiplcation
torch.matmul(f, g)

tensor([[ 87, 119],
        [ 65,  99]])

In [50]:
vector1 = torch.tensor([1, 2])
vector2 = torch.tensor([3, 4])

# dot product
torch.dot(vector1, vector2)

tensor(11)

In [51]:
# transpose
torch.transpose(f, 0, 1)

tensor([[5, 9],
        [7, 4],
        [3, 0]])

In [52]:
h = torch.randint(size=(3,3), low=0, high=10, dtype=torch.float32)
h

tensor([[5., 9., 8.],
        [9., 7., 9.],
        [2., 6., 7.]])

In [53]:
# determinant
torch.det(h)

tensor(-110.)

In [54]:
# inverse
torch.inverse(h)

tensor([[ 0.0455,  0.1364, -0.2273],
        [ 0.4091, -0.1727, -0.2455],
        [-0.3636,  0.1091,  0.4182]])

## 5. Comparison Operations


In [55]:
i = torch.randint(size=(2,3), low=0, high=10)
j = torch.randint(size=(2,3), low=0, high=10)

print(i)
print(j)

tensor([[7, 8, 3],
        [6, 1, 5]])
tensor([[5, 0, 4],
        [3, 8, 8]])


In [56]:
# greater than
i > j
# less than
i < j
# equal to
i == j
# not equal to
i != j
# greater than equal to

# less than equal to

tensor([[True, True, True],
        [True, True, True]])

## 6. Special Functions

In [57]:
k = torch.randint(size=(2,3), low=0, high=10, dtype=torch.float32)
k

tensor([[3., 3., 5.],
        [0., 6., 4.]])

In [58]:
# log
torch.log(k)

tensor([[1.0986, 1.0986, 1.6094],
        [  -inf, 1.7918, 1.3863]])

In [59]:
# exp
torch.exp(k)

tensor([[ 20.0855,  20.0855, 148.4132],
        [  1.0000, 403.4288,  54.5981]])

In [60]:
# sqrt
torch.sqrt(k)

tensor([[1.7321, 1.7321, 2.2361],
        [0.0000, 2.4495, 2.0000]])

In [61]:
# sigmoid
torch.sigmoid(k)

tensor([[0.9526, 0.9526, 0.9933],
        [0.5000, 0.9975, 0.9820]])

In [62]:
# softmax
torch.softmax(k, dim=0)

tensor([[0.9526, 0.0474, 0.7311],
        [0.0474, 0.9526, 0.2689]])

In [63]:
# relu
torch.relu(k)

tensor([[3., 3., 5.],
        [0., 6., 4.]])

## Inplace Operations

In [64]:
m = torch.rand(2,3)
n = torch.rand(2,3)

print(m)
print(n)

tensor([[0.6574, 0.3451, 0.0453],
        [0.9798, 0.5548, 0.6868]])
tensor([[0.4920, 0.0748, 0.9605],
        [0.3271, 0.0103, 0.9516]])


In [ ]:
m.add_(n) # _ means inplace Operation

tensor([[1.1494, 0.4199, 1.0058],
        [1.3069, 0.5650, 1.6384]])

In [66]:
m

tensor([[1.1494, 0.4199, 1.0058],
        [1.3069, 0.5650, 1.6384]])

In [67]:
n

tensor([[0.4920, 0.0748, 0.9605],
        [0.3271, 0.0103, 0.9516]])

In [68]:
torch.relu(m)

tensor([[1.1494, 0.4199, 1.0058],
        [1.3069, 0.5650, 1.6384]])

In [69]:
m.relu_()

tensor([[1.1494, 0.4199, 1.0058],
        [1.3069, 0.5650, 1.6384]])

In [70]:
m

tensor([[1.1494, 0.4199, 1.0058],
        [1.3069, 0.5650, 1.6384]])

## Copying a Tensor


In [71]:
a = torch.rand(2,3)
a

tensor([[0.2855, 0.2324, 0.9141],
        [0.7668, 0.1659, 0.4393]])

In [ ]:
b = a # Just pointing to same memory 

In [73]:
b

tensor([[0.2855, 0.2324, 0.9141],
        [0.7668, 0.1659, 0.4393]])

In [74]:
a[0][0] = 0

In [75]:
a

tensor([[0.0000, 0.2324, 0.9141],
        [0.7668, 0.1659, 0.4393]])

In [76]:
b

tensor([[0.0000, 0.2324, 0.9141],
        [0.7668, 0.1659, 0.4393]])

In [77]:
id(a)

1819284247312

In [78]:
id(b)

1819284247312

In [79]:
b = a.clone()

## Tensor Operations on GPU

In [80]:
torch.cuda.is_available()

True

In [81]:
device = torch.device('cuda')

In [82]:
# Create a new tensor on GPU 
torch.rand((2,3), device=device)

tensor([[0.3563, 0.0303, 0.7088],
        [0.2009, 0.0224, 0.9896]], device='cuda:0')

In [83]:
a = torch.rand(2,3)
a

tensor([[0.2243, 0.8935, 0.0497],
        [0.1780, 0.3011, 0.1893]])

In [85]:
b = a.to(device)

In [86]:
b + 5

tensor([[5.2243, 5.8935, 5.0497],
        [5.1780, 5.3011, 5.1893]], device='cuda:0')

# Compare CPU and GPU performance

In [88]:
import time 

#define the size of the matrices
size = 10000

#Create random matrices on CPU 
matrix_cpu1 = torch.randn(size, size) 
matrix_cpu2 = torch.randn(size, size)

#meature time on CPU
start_time = time.time() 
result_cpu = torch.matmul(matrix_cpu1, matrix_cpu2)
cpu_time = time.time() - start_time 

print(f"Time on CPU: {cpu_time: .4f} seconds") 

# Move matrices to GPU 
matrix_gpu1 = matrix_cpu1.to("cuda")
matrix_gpu2 = matrix_cpu2.to("cuda")

# Measure time on GPU 
start_time=time.time() 
result_gpu = torch.matmul(matrix_gpu1, matrix_gpu2) 
torch.cuda.synchronize() # Ensure all GPU Operations are complete
gpu_time = time.time() - start_time

print(f"Time on GPU: {gpu_time: .4f} seconds") 

#compare results 
print("\nSpeedup (CPU time/ GPU time):", cpu_time/gpu_time)

Time on CPU:  10.8370 seconds
Time on GPU:  0.9260 seconds

Speedup (CPU time/ GPU time): 11.702947445879042


## Reshaping Tensors

In [89]:
a = torch.ones(4,4)
a

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [90]:
# reshape
a.reshape(2,2,2,2)

tensor([[[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]],


        [[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]]])

In [91]:
#flatten
a.flatten()

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [93]:
b = torch.rand(2,3,4)
b

tensor([[[0.3651, 0.4549, 0.8776, 0.3721],
         [0.7827, 0.4926, 0.7323, 0.4682],
         [0.4369, 0.3151, 0.6987, 0.7903]],

        [[0.5187, 0.7766, 0.9718, 0.5460],
         [0.9329, 0.9847, 0.6817, 0.2420],
         [0.6212, 0.0121, 0.0662, 0.3254]]])

In [94]:
#permute 
b.permute(2,1,0).shape

torch.Size([4, 3, 2])

In [97]:
# unsqueeze 
c = torch.rand(226,226,3)
c.unsqueeze(0).shape

torch.Size([1, 226, 226, 3])

In [101]:
# squeeze 
d = torch.rand(1,20)
d.squeeze(0).shape

torch.Size([20])

## Numpy and Pytorch

In [102]:
import numpy as np

In [103]:
a = torch.tensor([1,2,3])
a

tensor([1, 2, 3])

In [104]:
b= a.numpy()

In [105]:
type(b)

numpy.ndarray

In [107]:
c = np.array([1,2,3])
c

array([1, 2, 3])

In [108]:
torch.from_numpy(c)

tensor([1, 2, 3], dtype=torch.int32)